server {
    listen 80;

    location / {
        root /usr/share/nginx/html;
        try_files $uri $uri/ /index.html;
    }

    location ~* ^/(auth|parties|challenge)(/.*)?$ {
        proxy_pass BACKEND_PLACEHOLDER;
        proxy_ssl_server_name on;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /ws/ {
        proxy_pass BACKEND_PLACEHOLDER/ws/;
        proxy_ssl_server_name on;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }
}
